# Generated by Django 4.0.6 on 2022-08-27 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0003_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health_Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campaign_Name', models.CharField(max_length=100)),
                ('Organizer_Name', models.CharField(max_length=50)),
                ('Venue', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Event_pic', models.FileField(default='', upload_to='pathology/picture')),
                ('Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
