# Generated by Django 4.0.6 on 2022-08-30 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0004_health_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('Test_Name', models.CharField(max_length=100)),
                ('Booking_Type', models.CharField(max_length=100)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('Phone', models.IntegerField(max_length=10)),
                ('Your_Query', models.TextField(max_length=500)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
